// parameter SWAP (ETH/USDC) - RATE (4%) - MATURITY (MARCH 2025)
// ERC20
// TOKEN NAME: POC ETH-USDC 4% MARCH-2025
// TOKEN SYMBOL: pocETHUSDC4MAR25
// DECIMALS: 18

// PARAMETER: DEBTTOKEN, COLLATERALTOKEN, RATE, MONTH (INT), YEAR (INT)

// MAPPING CONSTANTS
// JAN = JANUARY
// FEB = FEBRUARY
// MAR = MARCH
// APR = APRIL
// MAY = MAY
// JUN = JUNE
// JUL = JULY
// AUG = AUGUST
// SEP = SEPTEMBER
// OCT = OCTOBER
// NOV = NOVEMBER
// DEC = DECEMBER